### PR TITLE
changed reader.py

### PR DESCRIPTION
**Pull request by krishnacharya**
## 
Changes proposed in this pull request:
reader.py now returns a  dictionary with key(str) as 'yyyy-mm-dd' and value as another dictionary {"data":day_data,"channel":channel_name}

## Checks
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Any images?
input:
updatedread
inProgess:
inprogress
output:
opnew

## Notify reviewers
@rohangoel96

### CODE REVIEW

**Comment by rohangoel96** [comment]
I am sorry I am saying this again but please ensure for every new code you add you shouldn't break existig code.
For example you'll need to update : https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/analysis/network.py#L43
and https://github.com/prasadtalasila/IRCLogParser/blob/dev/Tester.py#L15

**Comment by krishnacharya** [comment]
Yes i will certainly change these in the next PR or do you want multiple commits in one

**Comment by krishnacharya** [comment]
left:after changes right: before changes
newvsold
This is just part of the whole graph(currently zoomed in 6x)

**Comment by rohangoel96** [comment]
This is totally messed up. 
Merged via other commit @ 757e32ccce9d9d661c64881bc40f1763b5bd9c7d

**Pull request closed without merging**
