### PR TITLE
adds unit tests for user.py

### LINKED ISSUE #203: add unit tests for lib/analysis/user.py

### PR DESCRIPTION
**Pull request by Kausam**
Adds unit-test for some functions of user.py
Fix #203  .

Changes proposed in this pull request:
- Adds unit-test for functions nick_change_graph, top_keywords_for_nick and extended_stop_words of user.py
- Corrects a small spelling mistake in saver.py
- Corrects the documentation comment about the return type of user.py

## Checks
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure you have added required documentation
- [x] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Notify reviewers
@rohangoel96

### CODE REVIEW

**Comment by kaushik-rohit** [comment]
@Kausam Why are there 2 commits with the exact same title? If the changes differ in both the commit please change the title or better squash the commits into one.

**Comment by Kausam** [comment]
@kaushik-rohit Is it okay now?

**Comment by kaushik-rohit** [comment]
@Kausam yes, also what you wrote are integration tests. You need to mock the outside dependencies while testing any function. Thatis what we are aiming at. If you can update it with mocked dependencies, it will be nice.

**Comment by kaushik-rohit** [comment]
Looks good to me.

**Comment by prasadtalasila** [comment]
@Kausam The recent changes made by @kaushik-rohit introduce merge conflicts and breaking changes into user.py. You need to rebase your branch and make modifications to the tests.

**Comment by Kausam** [comment]
@prasadtalasila Ok. I am working on it.

**Pull request closed without merging**
