### PR TITLE
improve reader

### PR DESCRIPTION
**Pull request by kaushik-rohit**
## What? Why?
Fix # . (Add Reference to the issue if any)

Changes proposed in this pull request:
- introduce class and use inheritance to reduce code repetition for readers.
- Integrate different readers in a single module

##Testing(briefly mention the tests you wrote in regard to the proposed changes)
- [ ] Characteristics of the input used for test (eg: logs duration, graph size, array size)
- [ ] Characteristics of the output used for test.

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Notify reviewers
@kaushik-rohit
@prasadtalasila

### CODE REVIEW

**Comment by prasadtalasila** [comment]
Suggestions:
1. Add unit tests
1. Remove the slack in_out/reader.py and change the import dependencies

**Comment by prasadtalasila** [comment]
@kaushik-rohit Will you be contributing to this PR and inching it towards completion? If you can't do this now, please close the PR. We can always reopen it later.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Yes, Sir. I have made few changes but still need to write the test cases, that would take some time. Should I close it now and reopen later (maybe in a 1-2 weeks)?

**Comment by prasadtalasila** [comment]
@kaushik-rohit Please push the latest updates to the PR branch on your fork. @bhuvangupta008 is interested in working on this PR. He can start from the current state.
@bhuvangupta008 Once you got the latest snapshot of the code, please close this PR.

**Pull request closed without merging**
