### PR TITLE
corrections to calculation of RT, CL and CRT statistics

### PR DESCRIPTION
**Pull request by prasadtalasila**
## What? Why?
The present calculation of CL and CRT assume an RTcutoff value of 9. The RTcutoff value is dependent on the channel and time period. Thus we need to calculate the RTcutoff value from the statistical distribution of the response time.

Fix # . (Add Reference to the issue if any)
#111 

Changes proposed in this pull request:
- channel.response_time() function returns rt_table and rt_cutoff_time. The cutoff time is computed in one of two ways.
    1. Using the percentile cutoff strategy (PERCENTILE): In this strategy, we specify a percentile statistical significance cutoff value (for example, 1%, 5%, 10% etc) for RT, CL and CRT. The cutoff time for RT determined using the given statistical significance becomes the RTcutoff value. New config variable named PERCENTILE introduced into config.py
        As mentioned before, the percentile configuration value is for truncating RT, CL and CRT tables.
    1. Using statistical coverage strategy (TWO_SIGMA): We compute the RTcutoff as RT_mean + 2*RT_std. The strategy itself is specified in the config.py file using the constant named CUTOFF_TIME_STRATEGY.
- New unit tests added in TDD compliant format for util.py and lib/analysis/channel.py

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure you have added required documentation
- [x] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Any images?
Not applicable

## Notify reviewers
@rohangoel96 @kaushik-rohit

### CODE REVIEW

**Comment by prasadtalasila** [comment]
At the moment, the newly created unit tests have boiler plate code for feeding in inputs from files. We can benefit from using ddt. However, this work is not a priority now; we can take up the same after the paper is pushed out.

**Comment by kaushik-rohit** [comment]
@prasadtalasila There seems to some issue as I am not able to generate the results. Also the exponential_curve_fit_and_plot / _x_shifted contains the intial filter param as well.
 `    conv_ref_time_curve_fit_parameters = vis.exponential_curve_fit_and_plot_x_shifted(conv_ref_time, 20, output_directory, "conv_ref_time")
  File "/home/irclogparser/IRCLogParser-conv/lib/vis.py", line 128, in exponential_curve_fit_and_plot_x_shifted
    x_pdf, y_pdf = generate_probability_distribution(data, initial_rows_filter)
  File "/home/irclogparser/IRCLogParser-conv/lib/vis.py", line 55, in generate_probability_distribution
    freq = [x/float(total) for x in topRows]
ZeroDivisionError: float division by zero
`

**Comment by prasadtalasila** [comment]
@kaushik-rohit As can be verified from the history page of vis.py file, this PR does not touch vis.py at all. 

The code fragment `vis.exponential_curve_fit_and_plot_x_shifted` that you mentioned is on [line-74 of sample.py](https://github.com/prasadtalasila/IRCLogParser/blob/conv-cutoffs/sample.py#L74). 

As per your comment, the error is being triggered on [line-77 of vis.py](https://github.com/prasadtalasila/IRCLogParser/blob/conv-cutoffs/lib/vis.py#L77) which is inside the function `vis.exponential_curve_fit_and_plot_x_shifted()`.

The only way it can throw an error is if the output format has changed. I am not immediately able to generate the outputs on this computer. Can you post the sample format of [line-63 of sample.py] for the latest commit of dev branch and the latest commit of conv-cutoffs branch.

thanks.

**Comment by rohangoel96** [comment]
can you please fix the code-climate issues so that we can review and merge?

**Comment by prasadtalasila** [comment]
The errors may be due to the way new outputs of conversation cutoffs are being handled in vis.py. We will know for sure when PR #140 runs on these updated channel.py functions.

We need the functions in vis.py to consider the following cases.

1. No. of elements in the passed list should be more than one for curve fit cases.

@rohangoel96 The solving the two code climate issues would require writing helper functions on unit test methods - not an advisable practice. Hence not fixing those two issues for now. As and when we use ddt on this unit test structure, the code climate warnings should go away.

**Pull request merged**
