### PR TITLE
network: add unit-tests

### PR DESCRIPTION
**Pull request by kaushik-rohit**
Changes proposed in this pull request:
- add unit-test for network module

## Checks
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure you have added required documentation
- [x] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Notify reviewers
@rohangoel96

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@kaushik-rohit The code coverage percenrage does not increase because of the new tests. Am I missing something here?

**Comment by prasadtalasila** [comment]
@kaushik-rohit any updates on this PR?

**Comment by kaushik-rohit** [comment]
@prasadtalasila The function for which unit-test is added was very small and hence there is no increase in the coverage, I will try to extend Bhuvan's work for network.py.

**Comment by prasadtalasila** [comment]
@kaushik-rohit I am closing this PR. Once there is a substantial increase in the code coverage for network.py, please open a fresh PR.

**Pull request closed without merging**
