### PR TITLE
Add network-util.py in lib/

### LINKED ISSUE #326: Wrapper class for networkx
A wrapper class networkx library using [Facade design pattern](https://en.wikipedia.org/wiki/Facade_pattern).

### PR DESCRIPTION
**Pull request by hrishikesh-dahiya**
## What? Why?
Fix #326 

Changes proposed in this pull request:
- Add network_util.py module (acts as a wrapper class for networkx)

## Checks
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refactoring screenshots below if the output is visual

## Notify reviewers
@prasadtalasila

### CODE REVIEW

**Comment by hrishikesh-dahiya** [comment]
Matplotlib3.x doesn't work below Python3.5 
What should be the procedure, should we upgrade the python platform or downgrade the matplotlib version? @prasadtalasila

**Comment by prasadtalasila** [comment]
@hrishikesh-dahiya please restrict this PR to facade for networkx. We will deal with matplotlib with another facade class. To answer your question though, my suggestion is to pick the highest compatible veraion of matplotlib with python 2.7.6 codebase we currently have.

**Comment by prasadtalasila** [comment]
@hrishikesh-dahiya I see the reason for build failure is the incomparibility of matplotlib. Please change [setup](https://github.com/prasadtalasila/IRCLogParser/blob/master/setup.py) to a compatible version of matplotlib. You can specify a precise version of matplotlib in setup.py. See the line for networkx in setup.py which declares a specific version of matplotlib library.

**Comment by hrishikesh-dahiya** [comment]
https://github.com/prasadtalasila/IRCLogParser/blob/e7ec0b9de8c7154ecf00cfb391652ff3e19d2119/test/integration-test/test_lib/test_analysis/test_user.py
test_keywords_clusters() is failing

**Comment by prasadtalasila** [comment]
@hrishikesh-dahiya 
Please put in an expected fail decoration before the failing tests that correspond to keyword clusters. The function is incorrect in parts and can be rectified later. The correct decoration to use is:  `@unittest.expectedFailure`.

**Pull request merged**
