### PR TITLE
network: add unit-test for network module

### LINKED ISSUE #227: create unit tests for network.py module

### PR DESCRIPTION
**Pull request by kaushik-rohit**
1) modify previous test to mock dependencies
2) introduce more unit-tests

## What? Why?
Fix #227 

Changes proposed in this pull request:
- update unit-tests

## Checks
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure you have added required documentation
- [x] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Notify reviewers
@rohangoel96

### CODE REVIEW

**Comment by kaushik-rohit** [comment]
@prasadtalasila The work is not complete but you can review the approach as well as current work.

**Comment by kaushik-rohit** [comment]
@prasadtalasila  It would nice if you can review and merge this. I still need to test 2-3 function but I can do that in a different PR. This is already a lot of changes.
Also, the reason for the decrease in user coverage is because now we are mocking the user dependencies while testing network due to which users functions are not called anymore during the test and hence reduction in coverage. Although this should be fixed with kausam's work.

**Comment by prasadtalasila** [comment]
@kaushik-rohit In the code I see that the previous integration tests have been replaced with the unit tests with mocks.

Have the previous tests been moved to integration test suite? If not, doing so would be advantageous for retaining the code coverage in integration tests.

**Comment by kaushik-rohit** [comment]
@prasadtalasila done. I have moved it to integration test.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Can you please review the update PR. I had to change a few things in util, which doesn't affect the codebase but makes testing easier. Also, I would need to add the corresponding slack network test but this PR is already too big.

**Comment by kaushik-rohit** [comment]
@prasadtalasila I have muted the print statements. I will open another PR for docs correction. You can merge this now.

**Comment by prasadtalasila** [comment]
@kaushik-rohit There is a decrease in code coverage for util.py and user.py. Is there any specific reason for it? If the change is due to your modifications of code in these two files, please open an issue stating so.

**Pull request merged**
