### PR TITLE
Major Refactor and Making Library Functions

### PR DESCRIPTION
**Pull request by rohangoel96**
Refactored Code
Less Code does same work
Easy to understand variable names
More comments
Output stored in a different directory and pwd is not flooded
Renamed files to a more sensible name
Automatically create required files/folders to hold output
Library Functions Implemented

### CODE REVIEW

**Comment by rohangoel96** [comment]
@prasadtalasila @dhruvshekhawa kindly have a look at this.

**Comment by prasadtalasila** [comment]
The code still has too many hardcoded conventions. For example, please see lines 9-11 and line 190 of parser-aggregate-graph.py. These name conventions would ideally come as input to the library function. 

You can probably put all the existing code into one library module as different functions. These functions can be called from the driver script based on requirement.

**Comment by rohangoel96** [comment]
Updated the PR @prasadtalasila

**Comment by rohangoel96** [comment]
Also I guess the images used in the wiki shouldn't be pushed along with code in the repo. They make the repo look ugly. Those images can be hosted on http://tinypic.com/ . If I delete the images as of now the links used in the wiki will be broken and I can't update the wiki as I lack the required permissions. Maybe @dhruvshekhawat can update the links in the wiki and then we can delete the images from the repo.

**Comment by prasadtalasila** [comment]
The wiki has a separate repository. The URL on the wiki page can be used to clone the wiki into a local repository. A subdirectory img/ can be created in the wiki repo and images can be linked from there. Please see https://github.com/prasadtalasila/PacketAnalyzer/wiki/Analyzer-Architecture for an example of this technique.

**Comment by prasadtalasila** [comment]
Once the images are safely in the wiki repo and properly linked, please feel free to delete the images from the main repository.

**Comment by rohangoel96** [comment]
@prasadtalasila, I'll surely do that wiki stuff sir and is there anything I should improve on the code before merging?

**Comment by prasadtalasila** [comment]
Making a library module is a good check point for the next commit. I have not gone through the complete code base and hence can't think of any further changes to be done before the merge.

**Comment by rohangoel96** [comment]
@prasadtalasila, sir I need to push some new code which implements a new function. As this has nothing to do with this PR, i would request if you could please merge this or tell me the points on which I can improve as I can't start a new PR until this one is either closed or merged. I would also like to change the directory structure which needs another pull request.

**Pull request merged**
