### PR TITLE
adds directory for slackware handling and code for its slackReader, s…

### PR DESCRIPTION
**Pull request by kaushik-rohit**
Changes proposed in this pull request:
- Add directory and code for slack analysis

## Checks
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure you have added required documentation
- [x] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Notify reviewers
@rohangoel96

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@rohit-kaushik please run the slackware logs through the code in this commit and check for any anomalies. Do upload the results in the shared folder.

**Comment by rohangoel96** [comment]
@kaushik-rohit If I am not wrong I see some 'data-files' being added with this PR. Can you please explain why? Thanks.

**Comment by prasadtalasila** [comment]
Those data files are in the test/ directory. They are for the unit tests.

**Comment by kaushik-rohit** [comment]
@prasadtalasila I realised that some of the python files are using config module like community and user, These files are also common for ubuntu and slack since they don't require parsing changes but when doing a slack analysis these should use the config in slack which is currently not specified.

**Comment by prasadtalasila** [comment]
The only way to solve this problem is to move the config out of lib to the top-level. If this is non-trivial, we can attempt it now. Otherwise, this is to be done later.

@rohangoel96 please pitch in with suggestions.

**Comment by prasadtalasila** [comment]
@kaushik-rohit for now it may be faster to make the lib/slack directory completely self-contained. Sanctity of results is very important; it is much preferable to have code repetition than to have incorrect results.

**Comment by prasadtalasila** [comment]
@kaushik-rohit and @rohangoel96 Please see the commits on [slack-gc](https://github.com/prasadtalasila/IRCLogParser/tree/slack-gc) branch for latest work from my side on slack. It builds upon the work done by @kaushik-rohit on this PR. 
If both of you are okay with the changes proposed there, we can probably close this PR.

**Comment by rohangoel96** [comment]
Hey! Yeah, moving of config does make sense. Although yes, it should be a trivial task but will take some time. Since we are already short on time, I would suggest completing tasks of higher priority than changing directory structures.

Regarding the commits by @prasadtalasila on the `slack-gc` branch it looks all cool to me..

**Comment by kaushik-rohit** [comment]
@prasadtalasila looks good to me.

**Comment by prasadtalasila** [comment]
changes pushed directly into commit e2dee6e. No need for this PR anymore.

**Pull request closed without merging**
